
server:
  port: 8080
  servlet:
    context-path: /youngforyou_admin_prod/
  tomcat:
      max-http-header-size: 8192


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.42.229.111:3306/yjnlifedb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      test-while-idle: true
      time-between-connect-error-millis: 6000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      max-wait: 60000
      use-unfair-lock: true
  redis:
    host: 121.42.229.111
    database: 0
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max_wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB




mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com/example/youngforyou/dao/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

logging:
  file:
    path: ./logs

